services:
  mysql: 
    build: .
    container_name: recipe_mysql
    ports:
      - "${MYSQL_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-password}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-recipe}"
      MYSQL_USER: "${MYSQL_USER:-recipe}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - recipe_db_network

networks:
  recipe_db_network:
    external: true
